Update ci-cd-pipeline.yml

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -18,20 +18,10 @@ jobs:
         with:
           java-version: '11'
 
-      # Commented out Maven steps since there's no pom.xml
-      # - name: Build with Maven
-      #   run: mvn clean install -f /home/swapnil/Project_SM_MultiCluster/actions-runner/_work/Project_SM_MultiCluster/Project_SM_MultiCluster/pom.xml
-
-      # - name: Run tests
-      #   run: mvn test -f /home/swapnil/Project_SM_MultiCluster/actions-runner/_work/Project_SM_MultiCluster/Project_SM_MultiCluster/pom.xml
-
-      # - name: SonarQube Scan
-      #   env:
-      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-      #   run: mvn sonar:sonar -f /home/swapnil/Project_SM_MultiCluster/actions-runner/_work/Project_SM_MultiCluster/Project_SM_MultiCluster/pom.xml
+      # Skipping Maven build step
 
       - name: Build Docker image
-        run: docker build -t swapi123/eks:latest .
+        run: docker build -t swapi123/eks:v1.0.0 .
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
@@ -40,11 +30,11 @@ jobs:
           password: ${{ secrets.DOCKER_PASSWORD }}
 
       - name: Push Docker image
-        run: docker push swapi123/eks:latest
+        run: docker push swapi123/eks:v1.0.0
 
       - name: Verify Image Push
         run: |
-          docker pull swapi123/eks:latest || echo "Image with 'latest' tag not found. Trying to pull all available tags."
+          docker pull swapi123/eks:v1.0.0 || echo "Image with 'v1.0.0' tag not found. Trying to pull all available tags."
           docker pull -a swapi123/eks || echo "No tags available for swapi123/eks"
           docker images
 
@@ -74,7 +64,7 @@ jobs:
           password: ${{ secrets.DOCKER_PASSWORD }}
 
       - name: Pull Docker image
-        run: docker pull swapi123/eks:latest
+        run: docker pull swapi123/eks:v1.0.0
 
       - name: Trivy Scan
-        run: trivy image --severity HIGH,CRITICAL swapi123/eks:latest
+        run: trivy image --severity HIGH,CRITICAL swapi123/eks:v1.0.0
