Update ci-cd-pipeline.yml

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -41,6 +41,14 @@ jobs:
       - name: Push Docker image
         run: docker push swapi123/eks:latest
 
+      - name: Verify Image Push
+        run: |
+          # Verify if the image with the latest tag is pushed successfully
+          docker pull swapi123/eks:latest || echo "Image with 'latest' tag not found. Trying to pull all available tags."
+          # Pull all available tags to check what versions are available
+          docker pull -a swapi123/eks || echo "No tags available for swapi123/eks"
+          docker images
+
       - name: Deploy to Kubernetes
         uses: actions/kubernetes-action@v1.0.0
         with:
