Update ci-cd-pipeline.yml

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -18,9 +18,24 @@ jobs:
         with:
           java-version: '11'
 
-      # Skipping Maven build step
+      # Ensure Dockerfile is in the root directory or specify the correct path
+      - name: Build Docker image
+        run: docker build -t swapi123/eks:v1.0.0 -f Dockerfile .
 
-      # Removed Docker image build, push, and verify steps
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Push Docker image
+        run: docker push swapi123/eks:v1.0.0
+
+      - name: Verify Image Push
+        run: |
+          docker pull swapi123/eks:v1.0.0 || echo "Image with 'v1.0.0' tag not found. Trying to pull all available tags."
+          docker pull -a swapi123/eks || echo "No tags available for swapi123/eks"
+          docker images
 
       - name: Set up kubectl
         uses: azure/setup-kubectl@v1
